on:
  push:

name: CI
jobs:
  nocommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@71cf2267d89c5cb81562390fa70a37fa40b1305e
      - name: "nocommit checker"
        uses: nobssoftware/nocommit@5c3cf9519fe40b80b0954d254085b67b532a5dc3

  nix-flake-check:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@71cf2267d89c5cb81562390fa70a37fa40b1305e
      - uses: cachix/install-nix-action@456688f15bc354bef6d396e4a35f4f89d40bf2b7
        with:
          enable_kvm: true
          extra_nix_config: "system-features = nixos-test benchmark big-parallel kvm"
      # Our private cache, feel free to substitute in a fork
      - uses: cachix/cachix-action@29121a2db12c7ff8b89724a8898ca20d33bb4ea3
        if: |
          ! (github.triggering_actor == 'dependabot[bot]' && github.repository == 'anteriorai/brrr')
        with:
          name: anterior-private
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: |
          nix run .#nix-flake-check-changed

  # Ensure nix flake show isnâ€™t broken
  nix-flake-show:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@71cf2267d89c5cb81562390fa70a37fa40b1305e
      # Use a different nix installer for safety
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@86a5f59de1021a60b96aabee99743e062ce4297a
      # No need for a cache
      - run: nix flake show
